#define WIN32_LEAN_AND_MEAN
#include <Windows.h>

#include "config.hpp"
#include "utils.hpp"
#include "ini.hpp"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>

namespace pb {

HINSTANCE g_hinst = nullptr;
bool      g_debug = false;

bool g_keep_fast_travel = true;
bool g_keep_death       = true;
bool g_log_effects      = true;
bool g_log_untracked    = false;
bool g_weapon_memory      = true;
bool g_persist_physick    = true;
bool g_session_persist    = false;

std::unordered_set<int> g_force_persist;
std::unordered_set<int> g_never_persist;
std::unordered_map<int, std::string> g_names;

namespace {

// Weapon item id -> name (EquipParamWeapon), embedded like g_names. Only the
// base rows (id % 100 == 0) are named; named_weapon() handles upgrade levels.
std::unordered_map<int, std::string> g_weapon_names;

// Generated by cmake/embed_names.cmake from the external/Paramdex submodule
// (ER/Names/*.txt). Each defines a byte array + length.
#include "speffect_names.inc" // kSpEffectNamesTxt / kSpEffectNamesTxtLen
#include "weapon_names.inc"   // kWeaponNamesTxt   / kWeaponNamesTxtLen

// Parse a Paramdex names blob: lines of "<id> <name>" (UTF-8; BOM or malformed
// lines are skipped). Entries overwrite existing map entries when `overlay`.
void parse_names_blob(const unsigned char* data, size_t len,
                      std::unordered_map<int, std::string>& out, bool overlay) {
    const char* p   = reinterpret_cast<const char*>(data);
    const char* end = p + len;
    while (p < end) {
        const char* eol = p;
        while (eol < end && *eol != '\n') ++eol;
        const char* q = p;
        long id = 0;
        bool has_id = false;
        while (q < eol && *q >= '0' && *q <= '9') {
            id = id * 10 + (*q - '0');
            ++q;
            has_id = true;
        }
        if (has_id && q < eol && (*q == ' ' || *q == '\t')) {
            while (q < eol && (*q == ' ' || *q == '\t')) ++q;
            const char* e = eol;
            while (e > q && (e[-1] == '\r' || e[-1] == ' ' || e[-1] == '\t')) --e;
            if (e > q) {
                if (overlay) out[static_cast<int>(id)] = std::string(q, e);
                else         out.emplace(static_cast<int>(id), std::string(q, e));
            }
        }
        p = eol + 1;
    }
}

// ---- .ini schema + auto-heal --------------------------------------------
// The DLL owns the canonical option list. On every start the loaded .ini is
// compared against it: missing options are re-added with their defaults,
// unknown/deprecated options are removed, and user values for known options
// are preserved verbatim. The file is rewritten ONLY when its option set
// differs from the schema, so hand-edited comments survive normal runs.

struct SchemaKey {
    const char* section;
    const char* key;
    const char* def;     // default, exactly as written into the .ini
    const char* comment; // '\n'-separated comment lines (without the "; ")
};

const SchemaKey kSchema[] = {
    { "persistence", "keep_after_fast_travel", "1",
      "Re-apply buffs after a fast travel. 1=on, 0=off." },
    { "persistence", "keep_after_death", "1",
      "Re-apply buffs after death/respawn. 1=on, 0=off." },
    { "persistence", "persist_physick_tears", "1",
      "Keep Flask of Wondrous Physick tear effects through death/fast travel\n"
      "like any other buff. Set to 0 if you consider that cheating.\n"
      "1=on, 0=off." },
    { "persistence", "force_persist_ids", "",
      "If you find any effect being disabled after death or travelling, you can\n"
      "include it below and it will persist next time.\n"
      "A list of effects can be found here:\n"
      "https://github.com/soulsmods/Paramdex/blob/master/ER/Names/SpEffectParam.txt\n"
      "example: force_persist_ids = 1821, 1823, 1826, 1828\n"
      "above example is \"Cragblade\"" },
    { "persistence", "never_persist_ids", "",
      "The opposite: effects you NEVER want re-applied, even though the mod\n"
      "tracks them (e.g. an overhaul effect that misbehaves). Beats every\n"
      "other rule. Same id list format as above." },
    { "weapon_memory", "remember_per_weapon", "1",
      "Remember which weapon-bound buffs (greases, blade spells) were on\n"
      "each weapon and re-apply them when you swap back to that weapon.\n"
      "1=on, 0=off.\n"
      "The bindings are also saved to PersistentBuffs.state.ini (per character),\n"
      "so a game restart doesn't erase buffs parked on a stowed weapon; they are\n"
      "restored on the next launch when remember_across_sessions (below) is on." },
    { "session", "remember_across_sessions", "0",
      "EXPERIMENTAL: save your active buffs (with remaining time) to\n"
      "PersistentBuffs.state.ini next to the DLL, and restore them on the next\n"
      "game launch for the same character -- buffs continue where they left off\n"
      "(time does not pass while the game is closed; infinite buffs stay\n"
      "infinite). Keyed by character name. 1=on, 0=off." },
    { "general", "debug_console", "0",
      "Open a debug console. 1=on, 0=off." },
    { "general", "log_effects", "1",
      "Diagnostic: log every SpEffect id that appears/disappears on the player.\n"
      "Keep this on, so possible bugs can be diagnosed from the log." },
    { "general", "log_untracked", "0",
      "Diagnostic: when a buff appears that the mod is NOT keeping (so it won't\n"
      "survive death/fast travel and won't be saved to the state file), log it\n"
      "ONCE with its name and the reason. Use this to find the id of a buff that\n"
      "isn't persisting (e.g. an overhaul consumable/AoW the auto-scan misses),\n"
      "then add that id to force_persist_ids. Off by default (only needed while\n"
      "diagnosing a missing buff). 1=on, 0=off." },
};

// Options that USED to exist -- removed with a specific reason in the log
// (anything else unknown is removed as plain "unknown").
struct DeprecatedKey { const char* section; const char* key; const char* why; };
const DeprecatedKey kDeprecated[] = {
    { "persistence", "restore_remaining_time",
      "buffs now ALWAYS restore with their remaining time" },
    { "persistence", "restore_buff_power",
      "re-applied buffs now ALWAYS keep their cast-time power" },
    { "persistence", "exclude_ids",
      "replaced by the source allowlist + never_persist_ids" },
    { "persistence", "persist_great_runes",
      "Great Rune persistence was removed (did not work as intended)" },
    { "persistence", "always_persist_ids",
      "the AoW self-buff list is built in now" },
    { "persistence", "reapply_delay_ms",
      "hard-coded (500 ms tuned value)" },
};

const SchemaKey* schema_find(const std::string& sec, const std::string& key) {
    for (const auto& k : kSchema)
        if (sec == k.section && key == k.key) return &k;
    return nullptr;
}

const char* deprecated_why(const std::string& sec, const std::string& key) {
    for (const auto& d : kDeprecated)
        if (sec == d.section && key == d.key) return d.why;
    return nullptr;
}

bool schema_def_bool(const char* section, const char* key) {
    const SchemaKey* k = schema_find(section, key);
    return k && std::strcmp(k->def, "1") == 0;
}

// Rewrite the .ini from the schema, preserving user values for known options.
// Returns true if the file was (re)written.
bool heal_config(const Ini& ini, bool file_existed) {
    std::vector<const SchemaKey*> missing;
    for (const auto& k : kSchema)
        if (!ini.has(k.section, k.key)) missing.push_back(&k);

    std::vector<std::pair<std::string, std::string>> extra; // (section, key)
    for (const auto& sec : ini.section_names())
        for (const auto& key : ini.keys_in(sec))
            if (!schema_find(sec, key)) extra.emplace_back(sec, key);

    if (file_existed && missing.empty() && extra.empty()) return false;

    std::ofstream f(config_path());
    if (!f) {
        flog("[WARN] config: .ini needs healing but the file is not writable");
        return false;
    }

    f << "; ============================================================\n";
    f << ";  PersistentBuffs v" << kModVersion << " -- configuration\n";
    f << ";  This file is auto-healed on every game start: missing options\n";
    f << ";  come back with their defaults, unknown options are removed,\n";
    f << ";  your values for known options are kept.\n";
    f << "; ============================================================\n";

    const char* cur_section = "";
    for (const auto& k : kSchema) {
        if (std::strcmp(cur_section, k.section) != 0) {
            cur_section = k.section;
            f << "\n[" << k.section << "]\n";
        }
        f << "\n";
        // comment block: one "; " prefix per line
        const char* c = k.comment;
        while (*c) {
            const char* nl = std::strchr(c, '\n');
            const size_t n = nl ? static_cast<size_t>(nl - c) : std::strlen(c);
            f << "; " << std::string(c, n) << "\n";
            c += n + (nl ? 1 : 0);
        }
        const std::string val = ini.has(k.section, k.key)
                                    ? ini.get_string(k.section, k.key)
                                    : std::string(k.def);
        f << k.key << " = " << val << "\n";
    }

    if (!file_existed) {
        flog("config: no .ini found -- wrote a fresh one with defaults");
        return true;
    }
    for (const auto* k : missing)
        flog("config: healed .ini -- added missing [%s] %s = %s (default)",
             k->section, k->key, *k->def ? k->def : "<empty>");
    for (const auto& [sec, key] : extra) {
        const char* why = deprecated_why(sec, key);
        if (why) flog("config: healed .ini -- removed deprecated [%s] %s (%s)",
                      sec.c_str(), key.c_str(), why);
        else     flog("config: healed .ini -- removed unknown [%s] %s",
                      sec.c_str(), key.c_str());
    }
    return true;
}

} // namespace

// Parse a list of integer ids from a string (any non-digit is a separator).
std::unordered_set<int> parse_id_list(const std::string& s) {
    std::unordered_set<int> out;
    std::string num;
    for (char c : s) {
        if (c >= '0' && c <= '9') { num += c; continue; }
        if (!num.empty()) { out.insert(std::atoi(num.c_str())); num.clear(); }
    }
    if (!num.empty()) out.insert(std::atoi(num.c_str()));
    return out;
}

size_t load_names() {
    g_names.clear();
    g_weapon_names.clear();
    // Baseline: the Paramdex names embedded at build time.
    parse_names_blob(kSpEffectNamesTxt, kSpEffectNamesTxtLen, g_names, false);
    parse_names_blob(kWeaponNamesTxt, kWeaponNamesTxtLen, g_weapon_names, false);
    // Optional overlay: a SpEffectParam.txt next to the DLL overrides/extends
    // the embedded list (overhaul mods' custom ids).
    std::ifstream f(names_path(), std::ios::binary);
    if (f) {
        const std::string blob((std::istreambuf_iterator<char>(f)),
                               std::istreambuf_iterator<char>());
        parse_names_blob(reinterpret_cast<const unsigned char*>(blob.data()),
                         blob.size(), g_names, true);
        flog("names: %zu SpEffect + %zu weapon names embedded, plus "
             "SpEffectParam.txt overrides next to the DLL",
             g_names.size(), g_weapon_names.size());
    } else {
        flog("names: %zu SpEffect + %zu weapon names embedded (Paramdex)",
             g_names.size(), g_weapon_names.size());
    }
    return g_names.size();
}

std::string named(int id) {
    const auto it = g_names.find(id);
    return it == g_names.end() ? std::to_string(id)
                               : std::to_string(id) + ":" + it->second;
}

std::string named_weapon(int id) {
    char buf[192];
    auto it = g_weapon_names.find(id);
    if (it != g_weapon_names.end()) {
        std::snprintf(buf, sizeof(buf), "%s (%d)", it->second.c_str(), id);
        return buf;
    }
    // Upgrade rows are base+level (base ids are multiples of 100); Paramdex
    // only names the base row.
    const int level = id % 100;
    it = g_weapon_names.find(id - level);
    if (it != g_weapon_names.end()) {
        std::snprintf(buf, sizeof(buf), "%s +%d (%d)", it->second.c_str(), level, id);
        return buf;
    }
    std::snprintf(buf, sizeof(buf), "#%d", id);
    return buf;
}

std::string join_ids(const std::vector<int>& ids) {
    std::string s;
    for (int id : ids) { s += named(id); s += ' '; }
    return s;
}

void load_config() {
    Ini ini;
    const bool loaded = ini.load(config_path());
    g_debug            = ini.get_bool("general", "debug_console",
                                      schema_def_bool("general", "debug_console"));
    g_log_effects      = ini.get_bool("general", "log_effects",
                                      schema_def_bool("general", "log_effects"));
    g_log_untracked    = ini.get_bool("general", "log_untracked",
                                      schema_def_bool("general", "log_untracked"));
    g_keep_fast_travel = ini.get_bool("persistence", "keep_after_fast_travel",
                                      schema_def_bool("persistence", "keep_after_fast_travel"));
    g_keep_death       = ini.get_bool("persistence", "keep_after_death",
                                      schema_def_bool("persistence", "keep_after_death"));
    g_persist_physick  = ini.get_bool("persistence", "persist_physick_tears",
                                      schema_def_bool("persistence", "persist_physick_tears"));
    g_weapon_memory    = ini.get_bool("weapon_memory", "remember_per_weapon",
                                      schema_def_bool("weapon_memory", "remember_per_weapon"));
    g_session_persist  = ini.get_bool("session", "remember_across_sessions",
                                      schema_def_bool("session", "remember_across_sessions"));
    // always_persist is hard-coded (g_always_persist); reapply delay is hard-coded
    // (kReapplyDelayMs). restore_remaining_time / restore_buff_power are core
    // behavior now (always on, no longer options).
    g_force_persist = parse_id_list(ini.get_string("persistence", "force_persist_ids", ""));
    g_never_persist = parse_id_list(ini.get_string("persistence", "never_persist_ids", ""));
    if (g_debug) { AllocConsole(); FILE* o=nullptr; freopen_s(&o, "CONOUT$", "w", stdout); }
    flog(loaded ? "config loaded from PersistentBuffs.ini"
                : "[WARN] .ini not found; using defaults");
    heal_config(ini, loaded);
    load_names();
    flog("settings:\n"
         "keep_after_fast_travel   = %d\n"
         "keep_after_death         = %d\n"
         "persist_physick_tears    = %d\n"
         "remember_per_weapon      = %d\n"
         "remember_across_sessions = %d\n"
         "log_effects              = %d\n"
         "log_untracked            = %d\n"
         "force_persist_ids        = %zu id(s)\n"
         "never_persist_ids        = %zu id(s)",
         g_keep_fast_travel, g_keep_death, g_persist_physick,
         g_weapon_memory, g_session_persist,
         g_log_effects, g_log_untracked,
         g_force_persist.size(), g_never_persist.size());
}

} // namespace pb
