#define WIN32_LEAN_AND_MEAN
#include <Windows.h>

#include "names.hpp"
#include "utils.hpp"

#include <cstdio>
#include <fstream>
#include <iterator>
#include <unordered_map>

namespace iwb {

namespace {

std::unordered_map<int, std::string> g_speffect_names; // SpEffectParam id -> name
std::unordered_map<int, std::string> g_goods_names;     // EquipParamGoods id -> name
std::unordered_map<int, std::string> g_magic_names;     // Magic id -> name

// Generated by cmake/embed_names.cmake from the external/Paramdex submodule
// (ER/Names/*.txt). Each defines a byte array + length.
#include "speffect_names.inc" // kSpEffectNamesTxt / kSpEffectNamesTxtLen
#include "goods_names.inc"    // kGoodsNamesTxt    / kGoodsNamesTxtLen
#include "magic_names.inc"    // kMagicNamesTxt    / kMagicNamesTxtLen

// Parse a Paramdex names blob: lines of "<id> <name>" (UTF-8; BOM or malformed
// lines are skipped). Entries overwrite existing map entries when `overlay`.
void parse_names_blob(const unsigned char* data, size_t len,
                      std::unordered_map<int, std::string>& out, bool overlay) {
    const char* p   = reinterpret_cast<const char*>(data);
    const char* end = p + len;
    while (p < end) {
        const char* eol = p;
        while (eol < end && *eol != '\n') ++eol;
        const char* q = p;
        long id = 0;
        bool has_id = false;
        while (q < eol && *q >= '0' && *q <= '9') {
            id = id * 10 + (*q - '0');
            ++q;
            has_id = true;
        }
        if (has_id && q < eol && (*q == ' ' || *q == '\t')) {
            while (q < eol && (*q == ' ' || *q == '\t')) ++q;
            const char* e = eol;
            while (e > q && (e[-1] == '\r' || e[-1] == ' ' || e[-1] == '\t')) --e;
            if (e > q) {
                if (overlay) out[static_cast<int>(id)] = std::string(q, e);
                else         out.emplace(static_cast<int>(id), std::string(q, e));
            }
        }
        p = eol + 1;
    }
}

// Optional loose override next to the DLL: <ParamName>.txt (same Paramdex
// format). Lets an overhaul user extend/override the embedded names without a
// rebuild. Missing file is fine (embedded set is used as-is).
void overlay_loose(const wchar_t* fname,
                   std::unordered_map<int, std::string>& out) {
    const std::wstring path = dir_of(module_path()) + L"\\" + fname;
    std::ifstream f(path, std::ios::binary);
    if (!f) return;
    const std::string blob((std::istreambuf_iterator<char>(f)),
                           std::istreambuf_iterator<char>());
    parse_names_blob(reinterpret_cast<const unsigned char*>(blob.data()),
                     blob.size(), out, /*overlay=*/true);
}

std::string lookup(const std::unordered_map<int, std::string>& m, int id) {
    const auto it = m.find(id);
    return it == m.end() ? std::to_string(id)
                         : std::to_string(id) + ":" + it->second;
}

} // namespace

size_t load_names() {
    g_speffect_names.clear();
    g_goods_names.clear();
    g_magic_names.clear();
    // Baseline: the Paramdex names embedded at build time.
    parse_names_blob(kSpEffectNamesTxt, kSpEffectNamesTxtLen, g_speffect_names, false);
    parse_names_blob(kGoodsNamesTxt,    kGoodsNamesTxtLen,    g_goods_names,    false);
    parse_names_blob(kMagicNamesTxt,    kMagicNamesTxtLen,    g_magic_names,    false);
    // Optional loose overrides next to the DLL (overhaul ids).
    overlay_loose(L"SpEffectParam.txt",  g_speffect_names);
    overlay_loose(L"EquipParamGoods.txt", g_goods_names);
    overlay_loose(L"Magic.txt",           g_magic_names);
    flog("names: %zu SpEffect + %zu goods + %zu magic names loaded (Paramdex, embedded)",
         g_speffect_names.size(), g_goods_names.size(), g_magic_names.size());
    return g_speffect_names.size();
}

std::string named_speffect(int id) { return lookup(g_speffect_names, id); }
std::string named_goods(int id)    { return lookup(g_goods_names, id); }
std::string named_magic(int id)    { return lookup(g_magic_names, id); }

} // namespace iwb
